In [7]:
#importing libraries

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [9]:
#importing dataset

In [12]:
file=pd.read_excel("C:/Users/vaish/OneDrive/Desktop/datasets and projects/Google ads hourly analysis 19th june.xlsx")

In [13]:
file

Sr no  Impressions   Clicks  Cost      CTR        CPC  Cold Leads   \
0   00:00:00          5941     356    594  0.0600   1.666667           11   
1   00:30:00          4511     180    451  0.0400   2.500000            9   
2   01:00:00          3378     101    338  0.0300   3.333333            6   
3   01:30:00           652      26     65  0.0400   2.500000            1   
4   02:00:00           421       8     42  0.0200   5.000000            0   
5   02:30:00           110       2     11  0.0200   5.000000            0   
6   03:00:00            56       1      6  0.0200   5.000000            0   
7   03:30:00            42       1      4  0.0120   8.333333            0   
8   04:00:00             3       0      0  0.0110   9.090909            0   
9   04:30:00             8       0      1  0.0190   5.263158            0   
10  05:00:00            95       1     10  0.0140   7.142857            0   
11  05:30:00            64       1      6  0.0200   5.000000            0   
12  06:00:00            26       0      3  0.0020  50.000000            0   
13  06:30:00           193       4     19  0.0200   5.000000            0   
14  07:00:00           236       5     24  0.0220   4.545455            0   
15  07:30:00           463      23     46  0.0500   2.000000            1   
16  08:00:00           896      54     90  0.0600   1.666667            2   
17  08:30:00           486      34     49  0.0700   1.428571            1   
18  09:00:00           785      71     79  0.0900   1.111111            1   
19  09:30:00          1245     149    125  0.1200   0.833333            2   
20  10:00:00          1755     228    176  0.1300   0.769231            3   
21  10:30:00          1865     106    187  0.0569   1.757469            4   
22  11:00:00          2658     399    266  0.1500   0.666667            5   
23  11:30:00          3255     391    326  0.1200   0.833333            7   
24  12:00:00          3284     427    328  0.1300   0.769231            6   
25  12:30:00          4651     558    465  0.1200   0.833333            9   
26  13:00:00          4895     685    490  0.1400   0.714286           10   
27  13:30:00          4752     665    475  0.1400   0.714286            9   
28  14:00:00          4665     606    467  0.1300   0.769231            9   
29  14:30:00          4958     694    496  0.1400   0.714286           10   
30  15:00:00          5320     745    532  0.1400   0.714286           10   
31  15:30:00          5968     836    597  0.1400   0.714286           12   
32  16:00:00          5673     794    567  0.1400   0.714286           11   
33  16:30:00          4865    1216    487  0.2500   0.400000            9   
34  17:00:00          6593    1055    659  0.1600   0.625000           13   
35  17:30:00          8945    1700    895  0.1900   0.526316           18   
36  18:00:00          8444    1773    844  0.2100   0.476190           17   
37  18:30:00          8452    1944    845  0.2300   0.434783           17   
38  19:00:00          8757    2277    876  0.2600   0.384615           17   
39  19:30:00          8968    1883    897  0.2100   0.476190           18   
40  20:00:00          9425    1414    943  0.1500   0.666667           19   
41  20:30:00          9120    1277    912  0.1400   0.714286           18   
42  21:00:00          8945    1431    895  0.1600   0.625000           18   
43  21:30:00          7863    1179    786  0.1500   0.666667           16   
44  22:00:00          7521    1203    752  0.1600   0.625000           15   
45  22:30:00          9632    1830    963  0.1900   0.526316           19   
46  23:00:00         10230    1739   1023  0.1700   0.588235           20   
47  23:30:00          9452    1512    945  0.1600   0.625000           19   

    Warm Leads  Hot Leads  
0          5.0          2  
1          4.0          2  
2          3.0          1  
3          NaN          0  
4          0.0          0  
5          0.0          0  
6          0.0          0  
7        

In [14]:
# checking null values

In [15]:
file.isnull().sum()

Sr no           0
Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             0
Cold Leads      0
Warm Leads      1
Hot Leads       0
dtype: int64

In [16]:
# filling the null values with average value

In [17]:
dataset=file.fillna(file.mean())

C:\Users\vaish\AppData\Local\Temp\ipykernel_10524\513826909.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  dataset=file.fillna(file.mean())


In [18]:
dataset

Sr no  Impressions   Clicks  Cost      CTR        CPC  Cold Leads   \
0   00:00:00          5941     356    594  0.0600   1.666667           11   
1   00:30:00          4511     180    451  0.0400   2.500000            9   
2   01:00:00          3378     101    338  0.0300   3.333333            6   
3   01:30:00           652      26     65  0.0400   2.500000            1   
4   02:00:00           421       8     42  0.0200   5.000000            0   
5   02:30:00           110       2     11  0.0200   5.000000            0   
6   03:00:00            56       1      6  0.0200   5.000000            0   
7   03:30:00            42       1      4  0.0120   8.333333            0   
8   04:00:00             3       0      0  0.0110   9.090909            0   
9   04:30:00             8       0      1  0.0190   5.263158            0   
10  05:00:00            95       1     10  0.0140   7.142857            0   
11  05:30:00            64       1      6  0.0200   5.000000            0   
12  06:00:00            26       0      3  0.0020  50.000000            0   
13  06:30:00           193       4     19  0.0200   5.000000            0   
14  07:00:00           236       5     24  0.0220   4.545455            0   
15  07:30:00           463      23     46  0.0500   2.000000            1   
16  08:00:00           896      54     90  0.0600   1.666667            2   
17  08:30:00           486      34     49  0.0700   1.428571            1   
18  09:00:00           785      71     79  0.0900   1.111111            1   
19  09:30:00          1245     149    125  0.1200   0.833333            2   
20  10:00:00          1755     228    176  0.1300   0.769231            3   
21  10:30:00          1865     106    187  0.0569   1.757469            4   
22  11:00:00          2658     399    266  0.1500   0.666667            5   
23  11:30:00          3255     391    326  0.1200   0.833333            7   
24  12:00:00          3284     427    328  0.1300   0.769231            6   
25  12:30:00          4651     558    465  0.1200   0.833333            9   
26  13:00:00          4895     685    490  0.1400   0.714286           10   
27  13:30:00          4752     665    475  0.1400   0.714286            9   
28  14:00:00          4665     606    467  0.1300   0.769231            9   
29  14:30:00          4958     694    496  0.1400   0.714286           10   
30  15:00:00          5320     745    532  0.1400   0.714286           10   
31  15:30:00          5968     836    597  0.1400   0.714286           12   
32  16:00:00          5673     794    567  0.1400   0.714286           11   
33  16:30:00          4865    1216    487  0.2500   0.400000            9   
34  17:00:00          6593    1055    659  0.1600   0.625000           13   
35  17:30:00          8945    1700    895  0.1900   0.526316           18   
36  18:00:00          8444    1773    844  0.2100   0.476190           17   
37  18:30:00          8452    1944    845  0.2300   0.434783           17   
38  19:00:00          8757    2277    876  0.2600   0.384615           17   
39  19:30:00          8968    1883    897  0.2100   0.476190           18   
40  20:00:00          9425    1414    943  0.1500   0.666667           19   
41  20:30:00          9120    1277    912  0.1400   0.714286           18   
42  21:00:00          8945    1431    895  0.1600   0.625000           18   
43  21:30:00          7863    1179    786  0.1500   0.666667           16   
44  22:00:00          7521    1203    752  0.1600   0.625000           15   
45  22:30:00          9632    1830    963  0.1900   0.526316           19   
46  23:00:00         10230    1739   1023  0.1700   0.588235           20   
47  23:30:00          9452    1512    945  0.1600   0.625000           19   

    Warm Leads  Hot Leads  
0     5.000000          2  
1     4.000000          2  
2     3.000000          1  
3     3.914894          0  
4     0.000000          0  
5     0.000000          0  
6     0.000000          0  
7     0.0

In [19]:
dataset.isnull().sum()

Sr no           0
Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             0
Cold Leads      0
Warm Leads      0
Hot Leads       0
dtype: int64

In [20]:
# data preprocessing

In [21]:
column_to_drop=['Sr no','CTR','CPC','Warm Leads']

In [22]:
newfile=dataset.drop(column_to_drop, axis=1)

In [23]:
newfile

Impressions   Clicks  Cost   Cold Leads   Hot Leads
0           5941     356    594           11          2
1           4511     180    451            9          2
2           3378     101    338            6          1
3            652      26     65            1          0
4            421       8     42            0          0
5            110       2     11            0          0
6             56       1      6            0          0
7             42       1      4            0          0
8              3       0      0            0          0
9              8       0      1            0          0
10            95       1     10            0          0
11            64       1      6            0          0
12            26       0      3            0          0
13           193       4     19            0          0
14           236       5     24            0          0
15           463      23     46            1          0
16           896      54     90            2          0
17           486      34     49            1          0
18           785      71     79            1          0
19          1245     149    125            2          0
20          1755     228    176            3          0
21          1865     106    187            4          1
22          2658     399    266            5          1
23          3255     391    326            7          1
24          3284     427    328            6          1
25          4651     558    465            9          1
26          4895     685    490           10          2
27          4752     665    475            9          2
28          4665     606    467            9          2
29          4958     694    496           10          2
30          5320     745    532           10          2
31          5968     836    597           12          2
32          5673     794    567           11          2
33          4865    1216    487            9          1
34          6593    1055    659           13          2
35          8945    1700    895           18          3
36          8444    1773    844           17          3
37          8452    1944    845           17          4
38          8757    2277    876           17          3
39          8968    1883    897           18          3
40          9425    1414    943           19          4
41          9120    1277    912           18          4
42          8945    1431    895           18          4
43          7863    1179    786           16          3
44          7521    1203    752           15          3
45          9632    1830    963           19          4
46         10230    1739   1023           20          4
47          9452    1512    945           19          4

In [24]:
#discriptive analysis

In [25]:
newfile.sum()

Impressions     200522
Clicks           31584
Cost             20057
Cold Leads         392
Hot Leads           73
dtype: int64

In [26]:
# Calculating average value

In [27]:
newfile.mean()

Impressions     4177.541667
Clicks           658.000000
Cost             417.854167
Cold Leads         8.166667
Hot Leads          1.520833
dtype: float64

In [28]:
X=newfile.iloc[:,:-3].values
Y=newfile.iloc[:,-3].values

In [29]:
X

array([[ 5941,   356],
       [ 4511,   180],
       [ 3378,   101],
       [  652,    26],
       [  421,     8],
       [  110,     2],
       [   56,     1],
       [   42,     1],
       [    3,     0],
       [    8,     0],
       [   95,     1],
       [   64,     1],
       [   26,     0],
       [  193,     4],
       [  236,     5],
       [  463,    23],
       [  896,    54],
       [  486,    34],
       [  785,    71],
       [ 1245,   149],
       [ 1755,   228],
       [ 1865,   106],
       [ 2658,   399],
       [ 3255,   391],
       [ 3284,   427],
       [ 4651,   558],
       [ 4895,   685],
       [ 4752,   665],
       [ 4665,   606],
       [ 4958,   694],
       [ 5320,   745],
       [ 5968,   836],
       [ 5673,   794],
       [ 4865,  1216],
       [ 6593,  1055],
       [ 8945,  1700],
       [ 8444,  1773],
       [ 8452,  1944],
       [ 8757,  2277],
       [ 8968,  1883],
       [ 9425,  1414],
       [ 9120,  1277],
       [ 8945,  1431],
       [ 78

In [30]:
Y

array([ 594,  451,  338,   65,   42,   11,    6,    4,    0,    1,   10,
          6,    3,   19,   24,   46,   90,   49,   79,  125,  176,  187,
        266,  326,  328,  465,  490,  475,  467,  496,  532,  597,  567,
        487,  659,  895,  844,  845,  876,  897,  943,  912,  895,  786,
        752,  963, 1023,  945], dtype=int64)

In [31]:
#decision tree classifier

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.05, random_state=0)

In [33]:
 print(X_train)

[[ 5320   745]
 [ 5673   794]
 [ 8452  1944]
 [ 6593  1055]
 [ 9425  1414]
 [   42     1]
 [   95     1]
 [   64     1]
 [ 5968   836]
 [ 4865  1216]
 [ 4752   665]
 [ 9452  1512]
 [ 3378   101]
 [10230  1739]
 [  785    71]
 [  463    23]
 [ 4665   606]
 [ 2658   399]
 [  896    54]
 [ 9120  1277]
 [ 1755   228]
 [ 8945  1431]
 [    3     0]
 [  193     4]
 [ 4651   558]
 [  110     2]
 [  486    34]
 [ 8945  1700]
 [  236     5]
 [ 8757  2277]
 [ 4511   180]
 [   26     0]
 [ 7863  1179]
 [ 3284   427]
 [   56     1]
 [ 3255   391]
 [ 8444  1773]
 [ 1865   106]
 [ 1245   149]
 [    8     0]
 [ 8968  1883]
 [ 9632  1830]
 [  652    26]
 [ 5941   356]
 [ 7521  1203]]


In [34]:
print(Y_train)

[ 532  567  845  659  943    4   10    6  597  487  475  945  338 1023
   79   46  467  266   90  912  176  895    0   19  465   11   49  895
   24  876  451    3  786  328    6  326  844  187  125    1  897  963
   65  594  752]


In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [36]:
X_train = sc.fit_transform(X_train)

In [37]:
X_test = sc.fit_transform(X_test)

In [38]:
from sklearn.tree import DecisionTreeClassifier

In [39]:
DT= DecisionTreeClassifier(criterion="gini", random_state=0)

In [40]:
DT.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=0)

In [41]:
print(DT.predict(sc.transform([[652,26]])))

[0]


In [42]:
# Predicting the Test set results

In [45]:
y_pred = DT.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))


[[659 496]
 [  0  42]
 [659 490]]


In [46]:
# Making the Confusion Matrix

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]


0.0

In [48]:
# Visualising the Training set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), Y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, DT.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Decision Tree Classification (Training set)')
plt.xlabel('Impressions')
plt.ylabel('Cost')
plt.legend()
plt.show()

In [ ]:
# Visualising the Test set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), Y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, DT.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Decision Tree Classification (Test set)')
plt.xlabel('Impressions')
plt.ylabel('Cost')
plt.legend()
plt.show()